create table if not exists public.awp_inventory (
    id bigint generated by default as identity primary key,
    model text not null unique,
    material_number text not null default '',
    product_group text not null default '',
    uk_stock integer not null default 0 check (uk_stock >= 0),
    on_water integer not null default 0 check (on_water >= 0),
    on_water_eta date,
    ordered integer not null default 0 check (ordered >= 0),
    machines_order_date date,
    egrd date,
    ordered_eta date,
    next_order integer not null default 0 check (next_order >= 0),
    next_order_date date,
    next_eta date,
    remark text not null default '',
    sort_order integer not null default 0,
    updated_at timestamptz not null default now()
);

alter table public.awp_inventory enable row level security;

-- The app uses a server-side service-role key stored in Streamlit Secrets.
-- No public read/write policy is required.
